// characters.js — 8 character configs with stats, abilities, and 3 theme objects each

const CHARACTERS = {
    frodo: {
        id: 'frodo',
        name: 'Frodo',
        title: 'Ring-bearer',
        abilityName: 'Ring of Power',
        abilityDesc: 'Become invisible & invincible',
        speed: 3.0,
        jumpForce: -12,
        abilityCooldown: 300,
        abilityDuration: 120,
        w: 28, h: 28,
        themes: [
            { // The Shire
                sky: ['#87CEEB', '#E0F0FF'],
                ground: '#4a7c2e',
                groundDark: '#3a6c1e',
                brick: '#c4a35a',
                brickDark: '#a08838',
                stone: '#888',
                stoneDark: '#666',
                platform: '#8B6914',
                spike: '#444',
                lava: '#cc0000',
                particles: 'leaves',
                particleColor: '#90EE90',
                bgLayers: [
                    { color: '#6b8f3a', yStart: 0.5, hills: true },
                    { color: '#5a7f2a', yStart: 0.6, hills: true },
                ],
            },
            { // Emyn Muil
                sky: ['#778899', '#B0C4DE'],
                ground: '#666',
                groundDark: '#555',
                brick: '#777',
                brickDark: '#555',
                stone: '#888',
                stoneDark: '#666',
                platform: '#555',
                spike: '#333',
                lava: '#444',
                particles: 'none',
                particleColor: '#aaa',
                bgLayers: [
                    { color: '#556', yStart: 0.4, hills: true },
                    { color: '#445', yStart: 0.55, hills: true },
                ],
            },
            { // Mount Doom
                sky: ['#1a0000', '#4a0000'],
                ground: '#333',
                groundDark: '#222',
                brick: '#444',
                brickDark: '#333',
                stone: '#555',
                stoneDark: '#333',
                platform: '#444',
                spike: '#ff4400',
                lava: '#ff4400',
                particles: 'ash',
                particleColor: '#ff6600',
                bgLayers: [
                    { color: '#2a0000', yStart: 0.3, hills: true },
                    { color: '#1a0000', yStart: 0.5, hills: true },
                ],
            },
        ],
    },

    aragorn: {
        id: 'aragorn',
        name: 'Aragorn',
        title: 'Ranger of the North',
        abilityName: 'Sword Dash',
        abilityDesc: 'Charge forward with Anduril',
        speed: 3.5,
        jumpForce: -12.5,
        abilityCooldown: 180,
        abilityDuration: 20,
        w: 28, h: 28,
        themes: [
            { // Weathertop
                sky: ['#2c1810', '#5a3520'],
                ground: '#5a4a3a',
                groundDark: '#4a3a2a',
                brick: '#6a5a4a',
                brickDark: '#5a4a3a',
                stone: '#777',
                stoneDark: '#555',
                platform: '#5a4a3a',
                spike: '#333',
                lava: '#cc0000',
                particles: 'fireflies',
                particleColor: '#ff8800',
                bgLayers: [
                    { color: '#3a2510', yStart: 0.4, hills: true },
                    { color: '#2a1505', yStart: 0.6, hills: true },
                ],
            },
            { // Helm's Deep
                sky: ['#1a1a2e', '#2a2a4e'],
                ground: '#666',
                groundDark: '#555',
                brick: '#888',
                brickDark: '#666',
                stone: '#999',
                stoneDark: '#777',
                platform: '#777',
                spike: '#444',
                lava: '#cc0000',
                particles: 'none',
                particleColor: '#aaa',
                bgLayers: [
                    { color: '#333', yStart: 0.3, hills: true },
                    { color: '#222', yStart: 0.5, hills: true },
                ],
            },
            { // Pelennor Fields
                sky: ['#2a2020', '#4a3030'],
                ground: '#5a5040',
                groundDark: '#4a4030',
                brick: '#6a6050',
                brickDark: '#5a5040',
                stone: '#777',
                stoneDark: '#555',
                platform: '#6a5040',
                spike: '#333',
                lava: '#cc0000',
                particles: 'ash',
                particleColor: '#888',
                bgLayers: [
                    { color: '#3a2a1a', yStart: 0.5, hills: true },
                    { color: '#2a1a0a', yStart: 0.65, hills: true },
                ],
            },
        ],
    },

    gandalf: {
        id: 'gandalf',
        name: 'Gandalf',
        title: 'The White',
        abilityName: 'Fireball',
        abilityDesc: 'Launch a bouncing fireball',
        speed: 2.8,
        jumpForce: -12,
        abilityCooldown: 90,
        abilityDuration: 0,
        w: 28, h: 28,
        themes: [
            { // Moria
                sky: ['#0a0a0a', '#1a1a1a'],
                ground: '#444',
                groundDark: '#333',
                brick: '#555',
                brickDark: '#444',
                stone: '#666',
                stoneDark: '#444',
                platform: '#555',
                spike: '#222',
                lava: '#ff4400',
                particles: 'fireflies',
                particleColor: '#ffaa00',
                bgLayers: [
                    { color: '#111', yStart: 0.3, hills: false },
                    { color: '#0a0a0a', yStart: 0.5, hills: false },
                ],
            },
            { // Fangorn
                sky: ['#1a3a1a', '#2a5a2a'],
                ground: '#3a5a2a',
                groundDark: '#2a4a1a',
                brick: '#5a7a3a',
                brickDark: '#4a6a2a',
                stone: '#666',
                stoneDark: '#555',
                platform: '#4a3a2a',
                spike: '#333',
                lava: '#006600',
                particles: 'leaves',
                particleColor: '#44aa22',
                bgLayers: [
                    { color: '#1a3a0a', yStart: 0.3, hills: true },
                    { color: '#0a2a00', yStart: 0.5, hills: true },
                ],
            },
            { // Minas Tirith
                sky: ['#dde', '#aab'],
                ground: '#ccc',
                groundDark: '#aaa',
                brick: '#ddd',
                brickDark: '#bbb',
                stone: '#eee',
                stoneDark: '#ccc',
                platform: '#bbb',
                spike: '#666',
                lava: '#cc0000',
                particles: 'none',
                particleColor: '#fff',
                bgLayers: [
                    { color: '#bbc', yStart: 0.4, hills: true },
                    { color: '#99a', yStart: 0.6, hills: true },
                ],
            },
        ],
    },

    legolas: {
        id: 'legolas',
        name: 'Legolas',
        title: 'Prince of Mirkwood',
        abilityName: 'Arrow Shot',
        abilityDesc: 'Fire a swift arrow',
        speed: 3.8,
        jumpForce: -13,
        abilityCooldown: 45,
        abilityDuration: 0,
        w: 28, h: 28,
        themes: [
            { // Mirkwood
                sky: ['#0a1a0a', '#1a3a1a'],
                ground: '#2a4a1a',
                groundDark: '#1a3a0a',
                brick: '#3a5a2a',
                brickDark: '#2a4a1a',
                stone: '#555',
                stoneDark: '#444',
                platform: '#3a2a1a',
                spike: '#1a1a00',
                lava: '#003300',
                particles: 'fireflies',
                particleColor: '#88ff44',
                bgLayers: [
                    { color: '#0a2a0a', yStart: 0.3, hills: true },
                    { color: '#001a00', yStart: 0.5, hills: true },
                ],
            },
            { // Lothlorien
                sky: ['#aaccee', '#ddeeff'],
                ground: '#5a8a3a',
                groundDark: '#4a7a2a',
                brick: '#aa9944',
                brickDark: '#998833',
                stone: '#aaa',
                stoneDark: '#888',
                platform: '#8a7a4a',
                spike: '#444',
                lava: '#2266aa',
                particles: 'leaves',
                particleColor: '#FFD700',
                bgLayers: [
                    { color: '#6a9a4a', yStart: 0.4, hills: true },
                    { color: '#5a8a3a', yStart: 0.6, hills: true },
                ],
            },
            { // Black Gate
                sky: ['#111', '#222'],
                ground: '#333',
                groundDark: '#222',
                brick: '#444',
                brickDark: '#333',
                stone: '#555',
                stoneDark: '#333',
                platform: '#444',
                spike: '#cc0000',
                lava: '#cc0000',
                particles: 'ash',
                particleColor: '#666',
                bgLayers: [
                    { color: '#1a1a1a', yStart: 0.3, hills: true },
                    { color: '#0a0a0a', yStart: 0.5, hills: true },
                ],
            },
        ],
    },

    gimli: {
        id: 'gimli',
        name: 'Gimli',
        title: 'Son of Gloin',
        abilityName: 'Ground Pound',
        abilityDesc: 'Slam down with seismic force',
        speed: 2.5,
        jumpForce: -11.5,
        abilityCooldown: 120,
        abilityDuration: 0,
        w: 28, h: 28,
        themes: [
            { // Glittering Caves
                sky: ['#1a1520', '#2a2530'],
                ground: '#555',
                groundDark: '#444',
                brick: '#666',
                brickDark: '#555',
                stone: '#777',
                stoneDark: '#555',
                platform: '#555',
                spike: '#333',
                lava: '#4488cc',
                particles: 'fireflies',
                particleColor: '#aaddff',
                bgLayers: [
                    { color: '#1a1520', yStart: 0.3, hills: false },
                    { color: '#0a0510', yStart: 0.5, hills: false },
                ],
            },
            { // Moria Depths
                sky: ['#050505', '#111'],
                ground: '#333',
                groundDark: '#222',
                brick: '#444',
                brickDark: '#333',
                stone: '#555',
                stoneDark: '#333',
                platform: '#444',
                spike: '#222',
                lava: '#ff6600',
                particles: 'fireflies',
                particleColor: '#ff8800',
                bgLayers: [
                    { color: '#0a0a0a', yStart: 0.3, hills: false },
                    { color: '#000', yStart: 0.5, hills: false },
                ],
            },
            { // Isengard
                sky: ['#2a2a2a', '#3a3a3a'],
                ground: '#555',
                groundDark: '#444',
                brick: '#666',
                brickDark: '#555',
                stone: '#777',
                stoneDark: '#555',
                platform: '#666',
                spike: '#333',
                lava: '#cc4400',
                particles: 'ash',
                particleColor: '#888',
                bgLayers: [
                    { color: '#222', yStart: 0.3, hills: true },
                    { color: '#111', yStart: 0.5, hills: true },
                ],
            },
        ],
    },

    sauron: {
        id: 'sauron',
        name: 'Sauron',
        title: 'The Dark Lord',
        abilityName: 'Dark Blast',
        abilityDesc: 'Wide area dark energy blast',
        speed: 3.2,
        jumpForce: -12,
        abilityCooldown: 150,
        abilityDuration: 0,
        w: 28, h: 28,
        themes: [
            { // Barad-dur
                sky: ['#0a0000', '#1a0500'],
                ground: '#222',
                groundDark: '#111',
                brick: '#333',
                brickDark: '#222',
                stone: '#444',
                stoneDark: '#222',
                platform: '#333',
                spike: '#ff2200',
                lava: '#ff4400',
                particles: 'ash',
                particleColor: '#ff4400',
                bgLayers: [
                    { color: '#1a0500', yStart: 0.3, hills: true },
                    { color: '#0a0000', yStart: 0.5, hills: true },
                ],
            },
            { // Mordor Plains
                sky: ['#1a0a00', '#2a1500'],
                ground: '#3a2a1a',
                groundDark: '#2a1a0a',
                brick: '#4a3a2a',
                brickDark: '#3a2a1a',
                stone: '#555',
                stoneDark: '#333',
                platform: '#4a3a2a',
                spike: '#ff2200',
                lava: '#ff4400',
                particles: 'ash',
                particleColor: '#cc3300',
                bgLayers: [
                    { color: '#2a1000', yStart: 0.4, hills: true },
                    { color: '#1a0500', yStart: 0.6, hills: true },
                ],
            },
            { // Mount Doom
                sky: ['#1a0000', '#3a0000'],
                ground: '#222',
                groundDark: '#111',
                brick: '#333',
                brickDark: '#222',
                stone: '#444',
                stoneDark: '#222',
                platform: '#333',
                spike: '#ff4400',
                lava: '#ff4400',
                particles: 'ash',
                particleColor: '#ff6600',
                bgLayers: [
                    { color: '#2a0000', yStart: 0.3, hills: true },
                    { color: '#1a0000', yStart: 0.5, hills: true },
                ],
            },
        ],
    },

    saruman: {
        id: 'saruman',
        name: 'Saruman',
        title: 'Of Many Colors',
        abilityName: 'Staff Beam',
        abilityDesc: 'Piercing beam of light',
        speed: 2.8,
        jumpForce: -12,
        abilityCooldown: 100,
        abilityDuration: 0,
        w: 28, h: 28,
        themes: [
            { // Orthanc
                sky: ['#1a1a1a', '#2a2a2a'],
                ground: '#333',
                groundDark: '#222',
                brick: '#444',
                brickDark: '#333',
                stone: '#666',
                stoneDark: '#444',
                platform: '#555',
                spike: '#222',
                lava: '#cc0000',
                particles: 'none',
                particleColor: '#888',
                bgLayers: [
                    { color: '#222', yStart: 0.3, hills: true },
                    { color: '#111', yStart: 0.5, hills: true },
                ],
            },
            { // Fangorn
                sky: ['#1a3a1a', '#2a5a2a'],
                ground: '#3a5a2a',
                groundDark: '#2a4a1a',
                brick: '#5a7a3a',
                brickDark: '#4a6a2a',
                stone: '#666',
                stoneDark: '#555',
                platform: '#4a3a2a',
                spike: '#333',
                lava: '#006600',
                particles: 'leaves',
                particleColor: '#44aa22',
                bgLayers: [
                    { color: '#1a3a0a', yStart: 0.3, hills: true },
                    { color: '#0a2a00', yStart: 0.5, hills: true },
                ],
            },
            { // The Shire (Corrupted)
                sky: ['#4a4030', '#6a5a40'],
                ground: '#4a4a2a',
                groundDark: '#3a3a1a',
                brick: '#5a5a3a',
                brickDark: '#4a4a2a',
                stone: '#666',
                stoneDark: '#555',
                platform: '#5a4a3a',
                spike: '#333',
                lava: '#884400',
                particles: 'ash',
                particleColor: '#665544',
                bgLayers: [
                    { color: '#4a3a20', yStart: 0.5, hills: true },
                    { color: '#3a2a10', yStart: 0.65, hills: true },
                ],
            },
        ],
    },

    gollum: {
        id: 'gollum',
        name: 'Gollum',
        title: 'Smeagol',
        abilityName: 'Stealth Leap',
        abilityDesc: 'Quick dash with brief invincibility',
        speed: 3.5,
        jumpForce: -13.5,
        abilityCooldown: 90,
        abilityDuration: 25,
        w: 24, h: 28,
        themes: [
            { // Misty Mountains
                sky: ['#667788', '#99aabb'],
                ground: '#777',
                groundDark: '#666',
                brick: '#888',
                brickDark: '#777',
                stone: '#999',
                stoneDark: '#777',
                platform: '#777',
                spike: '#444',
                lava: '#4488cc',
                particles: 'none',
                particleColor: '#ccc',
                bgLayers: [
                    { color: '#556677', yStart: 0.3, hills: true },
                    { color: '#445566', yStart: 0.5, hills: true },
                ],
            },
            { // Dead Marshes
                sky: ['#1a2a1a', '#2a3a2a'],
                ground: '#3a4a3a',
                groundDark: '#2a3a2a',
                brick: '#4a5a4a',
                brickDark: '#3a4a3a',
                stone: '#555',
                stoneDark: '#444',
                platform: '#4a4a3a',
                spike: '#2a3a1a',
                lava: '#336633',
                particles: 'fireflies',
                particleColor: '#88ff88',
                bgLayers: [
                    { color: '#1a2a1a', yStart: 0.4, hills: false },
                    { color: '#0a1a0a', yStart: 0.6, hills: false },
                ],
            },
            { // Shelob's Lair
                sky: ['#050505', '#0a0a0a'],
                ground: '#222',
                groundDark: '#111',
                brick: '#333',
                brickDark: '#222',
                stone: '#444',
                stoneDark: '#222',
                platform: '#333',
                spike: '#111',
                lava: '#330066',
                particles: 'none',
                particleColor: '#333',
                bgLayers: [
                    { color: '#0a0a0a', yStart: 0.3, hills: false },
                    { color: '#000', yStart: 0.5, hills: false },
                ],
            },
        ],
    },
};

const CHARACTER_ORDER = ['frodo', 'aragorn', 'gandalf', 'legolas', 'gimli', 'sauron', 'saruman', 'gollum'];
